### ISSUE TITLE
Openness in collaborations for improving visualization tools

### ISSUE THREAD

**Issue by damianooldoni** [jniedballa/camtrapR#13]
Hi @jniedballa. Before going too much in details, I would like to ask in this issue whether you are fine to accept PRs and actively give feedback for improving the visualization tools of camtrapR, which are quite basic at the moment.

At INBO they use already your package and therefore I find that improving this package is better than making a new one. In acse you are enthousiast about it, let me know and I will come in the future with some more specific issues.

**Comment by jniedballa** [comment]
Hi Damiano, 
thank you for the request. In principle yes, I wouldn't mind help in improving the visualisation tools in camtrapR. Can we please discuss first what you have in mind (here or via email)? 
So far I haven't dealt with PRs, so I'd need to familiarize myself first, since I'm also making ongoing improvements in the dev version.

**Comment by damianooldoni** [comment]
Nice to hear this from you. Thanks. I will come back to you with more specific questions then. I think during the next week(s). I will first gather the needs of Jim Caesar and his INBO team.

About pull requests, no rocket science behind them. Actually you need to make PRs at your own when you want to merge dev branch to master. The best way is to work linearly and in small steps (=relative little changes) in each branch/PR. In this way you, the reviewer, can easily check the changes.

You can maybe close this issue: I will then come back to you by opening more specific issues in the near future.
Cheers
Damiano

**Comment by jniedballa** [comment]
Hi, 
thank you for the information. I'll close this issue for now.
Please be aware that there is some old, unused and commented code in the detectionMaps for plotting in the maps in ggplot2. I didn't use it because I was trying to keep the number of dependencies to a minimum. On the other hand, having ggplot2 as a dependency is not a problem because most users will have it installed anyways.
Optionally, one could use geom_sf() to plot spatial objects. That would require creating sf objects instead of sp objects. That in turn would allow to easily use leaflet, mapview or some similar approach to create interactive maps with the camera traps overlaid on various base maps, which might be quite useful. 
Cheers,
Jürgen
